export enum CarBodyTypes{

  SEDAN='SEDAN',
  COUPE='COUPE',
  SPORTS_CAR='SPORTS_CAR',
  STATION_WAGON='STATION_WAGON',
  HATCHBACK='HATCHBACK',
  CONVERTIBLE='CONVERTIBLE',
  MINIVAN='MINIVAN',
  PICKUP='PICKUP',
  SUV='SUV'


}
