package com.implemica.model.car.entity;

public enum CarBrands {
    AUDI("AUDI"), ACURA("ACURA"), ALFA("ALFA"), ROMEO("ROMEO"),
    ASTON_MARTIN("ASTON_MARTIN"), BENTLEY("BENTLEY"), BYD("BYD"), BMW("BMW"),
    BRILLIANCE("BRILLIANCE"), BUICK("BUICK"), BUGATTI("BUGATTI"),
    CADILLAC("CADILLAC"), CHANGAN("CHANGAN"),  CHEVROLET("CHEVROLET"),
    CHERY("CHERY"), CHRYSLER("CHRYSLER"), CITROEN("CITROEN"), DAEWOO("DAEWOO"),
    DACIA("DACIA"), DAIHATSU("DAIHATSU"), DODGE("DODGE"), FAW("FAW"),
    FERRARI("FERRARI"), FIAT("FIAT"), FORD("FORD"), GEELY("GEELY"),
    GMC("GMC"), GREAT_WALL("GREAT_WALL"), HONDA("HONDA"), HUMMER("HUMMER"),
    HYUNDAI("HYUNDAI"), INFINITI("INFINITI"), JAGUAR("JAGUAR"), JEEP("JEEP"),
    KIA("KIA"), LAMBORGHINI("LAMBORGHINI"), LAND_ROVER("LAND_ROVER"),
    LANCIA("LANCIA"), LEXUS("LEXUS"), LIFAN("LIFAN"), LINCOLN("LINCOLN"),
    LOTUS("LOTUS"), MARUSSIA("MARUSSIA"), MAYBACH("MAYBACH"), MAZDA("MAZDA"),
    MERCEDES("MERCEDES"), MASERATI("MASERATI"), MINI("MINI"), MCLAREN("MCLAREN"),
    MITSUBISHI("MITSUBISHI"), NISSAN("NISSAN"), OPEL("OPEL"), PEUGEOT("PEUGEOT"),
    PORSCHE("PORSCHE"), RENAULT("RENAULT"), SAAB("SAAB"), SEAT("SEAT"),
    SKODA("SKODA"), SUBARU("SUBARU"), SUZUKI("SUZUKI"), TOYOTA("TOYOTA"),
    PONTIAC("PONTIAC"), ROLLS_ROYCE("ROLLS_ROYCE"), SMART("SMART"),
    SSANGYONG("SSANGYONG"), TESLA("TESLA"), VOLVO("VOLVO"), DATSUN("DATSUN"),
    VOLKSWAGEN("VOLKSWAGEN"), TAGAZ("TAGAZ"), HAVAL_ROVER("HAVAL_ROVER"),
    GENESIS("GENESIS");
    
    private final String stringValue;

    CarBrands(String stringValue) {
        this.stringValue = stringValue;
    }
    
    public String getStringValue(){
        return stringValue;
    }
}
