/*
 * API Car catalog V1.0
 * This is API for work with the car catalog server. For this sample, you can use the JWT to test the authorization filters and perform authorized requests to server like add ordelete car. You should put your JWT token with prefix \"Bearer \" in authorise filed to authorize. Also, there are examples of request and response that you can use for test API. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: welcome@implemica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AuthResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AuthorizationApiApi
 */
@Ignore
public class AuthorizationApiApiTest {

    private final AuthorizationApiApi api = new AuthorizationApiApi();

    /**
     * Get token by login and password.
     *
     * Get a token to work with the API by login and password of the registered user
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void loginUsingPOSTTest() throws Exception {
        String username = null;
        String password = null;
        AuthResponse response = api.loginUsingPOST(username, password);

        // TODO: test validations
    }
}
