/*
 * API Car catalog V1.0
 * This is API for work with the car catalog server. For this sample, you can use the JWT to test the authorization filters and perform authorized requests to server like add ordelete car. You should put your JWT token with prefix \"Bearer \" in authorise filed to authorize. Also, there are examples of request and response that you can use for test API. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: welcome@implemica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import java.io.File;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ImageApiApi
 */
@Ignore
public class ImageApiApiTest {

    private final ImageApiApi api = new ImageApiApi();

    /**
     * Delete image.
     *
     * Deletes car image by their name if image is not found returns 404 http status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteFileUsingDELETETest() throws Exception {
        String imageFileId = null;
        api.deleteFileUsingDELETE(imageFileId);

        // TODO: test validations
    }
    /**
     * Upload image.
     *
     * Loads the image to AWS S3 and set image id to this file, if not a graft extension, returns 400 http status.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadFileUsingPOSTTest() throws Exception {
        String imageFileNameThatHasCarAndGetFromAWSS3ByItsImageFileId = null;
        File imageFile = null;
        api.uploadFileUsingPOST(imageFileNameThatHasCarAndGetFromAWSS3ByItsImageFileId, imageFile);

        // TODO: test validations
    }
}
